#!MANAGED-CONFIG https://raw.githubusercontent.com/danialmd81/my-subscribtion/main/src/surfboard/hysteria.conf interval=60 strict=true interval=1440 strict=false
[General]
dns-server = system, 8.8.8.8, 8.8.4.4, 1.1.1.1, 1.0.0.1
doh-server = https://doh.pub/dns-query
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
proxy-test-url = https://www.youtube.com/favicon.ico
internet-test-url = http://www.gstatic.cn/generate_204
always-real-ip = stun.l.google.com
udp-policy-not-supported-behaviour = DIRECT
test-timeout = 1

[Proxy]

[Proxy Group]
myGroup = select

[Rule]
DOMAIN-SUFFIX,ir,DIRECT
GEOIP,IR,DIRECT
DOMAIN-SET,https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/surge_domainset_ads.txt,REJECT,update-interval=432000
DOMAIN-SET,https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/surge_domainset_other.txt,DIRECT,update-interval=432000
FINAL,myGroup
